//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aim.WireFormingStudio.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WireFormingStudioStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WireFormingStudioStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aim.WireFormingStudio.Languages.WireFormingStudioStrings", typeof(WireFormingStudioStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string BenderController_TabView_Header {
            get {
                return ResourceManager.GetString("BenderController_TabView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string BenderController_View_Title {
            get {
                return ResourceManager.GetString("BenderController_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Port.
        /// </summary>
        public static string EsViewPort_TabView_Header {
            get {
                return ResourceManager.GetString("EsViewPort_TabView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Port.
        /// </summary>
        public static string EsViewPort_TabView_Title {
            get {
                return ResourceManager.GetString("EsViewPort_TabView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Port.
        /// </summary>
        public static string EsViewPort_View_Title {
            get {
                return ResourceManager.GetString("EsViewPort_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Generic_AddButtonLabel {
            get {
                return ResourceManager.GetString("Generic_AddButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_CancelButtonLabel {
            get {
                return ResourceManager.GetString("Generic_CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Generic_CloseButtonLabel {
            get {
                return ResourceManager.GetString("Generic_CloseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Generic_OkButtonLabel {
            get {
                return ResourceManager.GetString("Generic_OkButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string MainView_StatusBar_ReadyStatusMessage {
            get {
                return ResourceManager.GetString("MainView_StatusBar_ReadyStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire Forming Studio.
        /// </summary>
        public static string MainView_Title {
            get {
                return ResourceManager.GetString("MainView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Editor.
        /// </summary>
        public static string SmartEditor_TabView_Header {
            get {
                return ResourceManager.GetString("SmartEditor_TabView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Editor.
        /// </summary>
        public static string SmartEditor_TabView_Title {
            get {
                return ResourceManager.GetString("SmartEditor_TabView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Editor.
        /// </summary>
        public static string SmartEditor_View_Title {
            get {
                return ResourceManager.GetString("SmartEditor_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Model.
        /// </summary>
        public static string ViewPort_RibbonMenu_LineModelGroup_Label {
            get {
                return ResourceManager.GetString("ViewPort_RibbonMenu_LineModelGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Model.
        /// </summary>
        public static string ViewPort_RibbonMenu_LineModelGroup_ToolTipLabel {
            get {
                return ResourceManager.GetString("ViewPort_RibbonMenu_LineModelGroup_ToolTipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Model Commands.
        /// </summary>
        public static string ViewPort_RibbonMenu_LineModelGroup_ToolTipText {
            get {
                return ResourceManager.GetString("ViewPort_RibbonMenu_LineModelGroup_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ViewPort_RibbonMenu_LoadLineModelButtonLabel {
            get {
                return ResourceManager.GetString("ViewPort_RibbonMenu_LoadLineModelButtonLabel", resourceCulture);
            }
        }
    }
}
